# Generated by Django 5.1.2 on 2025-10-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Subunidade')),
                ('sigla', models.CharField(blank=True, max_length=10, verbose_name='Sigla')),
                ('responsavel', models.CharField(blank=True, max_length=200, verbose_name='Responsável')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunidades', to='core.diretoria')),
            ],
            options={
                'verbose_name': 'Subunidade',
                'verbose_name_plural': 'Subunidades',
                'ordering': ['nome'],
            },
        ),
    ]
