# Generated by Django 5.2.7 on 2025-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/', verbose_name='Arquivo CSV')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('parcial', 'Sucesso Parcial')], default='processando', max_length=15, verbose_name='Status')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total de Registros')),
                ('registros_sucesso', models.IntegerField(default=0, verbose_name='Registros com Sucesso')),
                ('registros_erro', models.IntegerField(default=0, verbose_name='Registros com Erro')),
                ('log_erros', models.TextField(blank=True, verbose_name='Log de Erros')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
            ],
            options={
                'verbose_name': 'Importação de Indicadores',
                'verbose_name_plural': 'Importações de Indicadores',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorContratual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do Indicador')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Indicador')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('economico', 'Econômico-Financeiro'), ('contabil', 'Contábil'), ('tecnico', 'Técnico'), ('operacional', 'Operacional'), ('qualidade', 'Qualidade do Serviço')], max_length=15, verbose_name='Tipo')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('forma_visualizacao', models.CharField(choices=[('grafico_barras', 'Gráfico de Barras'), ('grafico_linhas', 'Gráfico de Linhas'), ('grafico_pizza', 'Gráfico de Pizza'), ('tabela', 'Tabela'), ('numero', 'Número Simples')], max_length=20, verbose_name='Forma de Visualização')),
                ('formula_calculo', models.TextField(blank=True, verbose_name='Fórmula de Cálculo')),
                ('periodicidade', models.CharField(max_length=20, verbose_name='Periodicidade de Coleta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Indicador Ativo')),
                ('ordem_exibicao', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Indicador Contratual',
                'verbose_name_plural': 'Indicadores Contratuais',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ValorIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_referencia', models.DateField(verbose_name='Período de Referência')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valor')),
                ('valor_meta', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor Meta')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_coleta', models.DateTimeField(auto_now_add=True, verbose_name='Data de Coleta')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Valor de Indicador',
                'verbose_name_plural': 'Valores de Indicadores',
                'ordering': ['-periodo_referencia'],
            },
        ),
    ]
