# Generated by Django 5.2.7 on 2025-10-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicadores', '0001_initial'),
        ('instrumentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoindicadores',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='valorindicador',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores_indicadores', to='instrumentos.instrumento', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='valorindicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='indicadores.indicadorcontratual', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='valorindicador',
            name='responsavel_coleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Coleta'),
        ),
        migrations.AlterUniqueTogether(
            name='valorindicador',
            unique_together={('indicador', 'contrato', 'periodo_referencia')},
        ),
    ]
