# Generated by Django 5.1.2 on 2026-05-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instrumentos', '0006_remove_instrumento_subunidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Endpoint')),
                ('url_relativa', models.CharField(help_text='Ex: /api/v1/clientes', max_length=500, verbose_name='URL Relativa')),
                ('metodo_http', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10, verbose_name='Método HTTP')),
                ('parametros_default', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros Default (JSON)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Endpoint Ativo')),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Dashboard')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('configuracao_layout', models.JSONField(blank=True, default=dict, verbose_name='Configuração de Layout')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_criados', to=settings.AUTH_USER_MODEL)),
                ('diretoria_proprietaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_proprios', to='core.diretoria')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acesso', models.CharField(choices=[('leitura', 'Somente Leitura'), ('colaboracao', 'Colaboração (Edição)')], default='leitura', max_length=20, verbose_name='Nível de Acesso')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diretoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards_compartilhados_recebidos', to='core.diretoria')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='integracao_dados.dashboard')),
            ],
            options={
                'verbose_name': 'Compartilhamento Analítico',
                'verbose_name_plural': 'Compartilhamentos Analíticos',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Dataset')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dados', models.JSONField(default=list, help_text='Estrutura tabular/lista de objetos', verbose_name='Dados Processados')),
                ('schema', models.JSONField(blank=True, default=dict, verbose_name='Schema (Metadados)')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('diretoria_proprietaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets_proprios', to='core.diretoria')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets_gerenciados', to=settings.AUTH_USER_MODEL)),
                ('endpoint_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='integracao_dados.endpoint')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FonteDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Fonte')),
                ('tipo', models.CharField(choices=[('api_rest', 'API REST'), ('banco_dados', 'Banco de Dados (SQL)'), ('arquivo_csv', 'Arquivo CSV'), ('planilha', 'Planilha Eletrônica')], max_length=50, verbose_name='Tipo da Fonte')),
                ('url_base', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Base')),
                ('metodo_autenticacao', models.CharField(choices=[('none', 'Sem Autenticação'), ('basic', 'Basic Auth'), ('jwt', 'Token JWT'), ('api_key', 'API Key'), ('oauth2', 'OAuth 2.0')], default='none', max_length=50, verbose_name='Método de Autenticação')),
                ('status_integracao', models.BooleanField(default=True, verbose_name='Integração Ativa')),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=200, verbose_name='Responsável Técnico')),
                ('frequencia_minutos', models.IntegerField(default=1440, help_text='1440 = 1 dia', verbose_name='Frequência de Sincronização (minutos)')),
                ('timeout_segundos', models.IntegerField(default=30, verbose_name='Timeout (segundos)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('diretoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_dados', to='core.diretoria')),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='integracao_dados.fontedados'),
        ),
        migrations.CreateModel(
            name='CredencialFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_api', models.CharField(blank=True, max_length=200, verbose_name='Usuário / Client ID')),
                ('senha_api', models.CharField(blank=True, max_length=200, verbose_name='Senha / Client Secret')),
                ('token_atual', models.TextField(blank=True, verbose_name='Token JWT / API Key')),
                ('headers_customizados', models.JSONField(blank=True, default=dict, verbose_name='Headers Customizados (JSON)')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração do Token')),
                ('fonte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais', to='integracao_dados.fontedados')),
            ],
            options={
                'verbose_name': 'Credencial de Fonte',
                'verbose_name_plural': 'Credenciais de Fontes',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Sincronização')),
                ('payload_original', models.JSONField(default=dict, verbose_name='Payload Original')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('processando', 'Processando')], max_length=20, verbose_name='Status')),
                ('tempo_execucao_ms', models.IntegerField(default=0, verbose_name='Tempo de Execução (ms)')),
                ('quantidade_registros', models.IntegerField(default=0, verbose_name='Quantidade de Registros')),
                ('log_erro', models.TextField(blank=True, verbose_name='Log de Erro')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='integracao_dados.endpoint')),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='VinculoObrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vinculo', models.CharField(choices=[('monitoramento_operacional', 'Monitoramento Operacional'), ('monitoramento_regulatorio', 'Monitoramento Regulatório'), ('fiscalizacao', 'Fiscalização'), ('acompanhamento_contratual', 'Acompanhamento Contratual')], default='monitoramento_regulatorio', max_length=50, verbose_name='Tipo de Vínculo')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa Técnica')),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_obrigacao', to='integracao_dados.dashboard')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_obrigacao', to='integracao_dados.dataset')),
                ('obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_analiticos', to='instrumentos.obrigacao')),
            ],
            options={
                'verbose_name': 'Vínculo Regulatório',
                'verbose_name_plural': 'Vínculos Regulatórios',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Widget')),
                ('tipo', models.CharField(choices=[('kpi', 'Indicador Numérico (KPI)'), ('linha', 'Gráfico de Linha'), ('barra', 'Gráfico de Barras'), ('pizza', 'Gráfico de Pizza'), ('tabela', 'Tabela de Dados')], max_length=50, verbose_name='Tipo do Gráfico')),
                ('configuracao', models.JSONField(default=dict, verbose_name='Configuração do Gráfico (Eixos, Filtros)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='integracao_dados.dashboard')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='integracao_dados.dataset')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['ordem'],
            },
        ),
    ]
