# Generated by Django 5.1.2 on 2026-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpoint',
            options={'ordering': ['nome'], 'verbose_name': 'Endpoint', 'verbose_name_plural': 'Endpoints'},
        ),
        migrations.AddField(
            model_name='credencialfonte',
            name='api_key_header',
            field=models.CharField(blank=True, default='X-API-Key', help_text='Nome do header onde a API Key deve ser enviada. Ex: X-API-Key, Authorization', max_length=100, verbose_name='Nome do Header da API Key'),
        ),
        migrations.AddField(
            model_name='credencialfonte',
            name='ultima_renovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Renovação do Token'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='content_type',
            field=models.CharField(blank=True, default='application/json', max_length=100, verbose_name='Content-Type'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='headers_override',
            field=models.JSONField(blank=True, default=dict, verbose_name='Headers Extras (sobrepõe os globais)'),
        ),
        migrations.AddField(
            model_name='fontedados',
            name='auth_content_type',
            field=models.CharField(blank=True, default='application/json', help_text='Ex: application/json ou application/x-www-form-urlencoded', max_length=100, verbose_name='Content-Type do Login'),
        ),
        migrations.AddField(
            model_name='fontedados',
            name='auth_metodo',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='POST', max_length=10, verbose_name='Método HTTP do Login'),
        ),
        migrations.AddField(
            model_name='fontedados',
            name='auth_payload_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Campos adicionais além de username/password. Ex: {"grant_type": "password"}', verbose_name='Payload Extra de Login (JSON)'),
        ),
        migrations.AddField(
            model_name='fontedados',
            name='auth_token_key',
            field=models.CharField(blank=True, default='access_token', help_text='Nome da chave JSON que contém o token. Ex: access_token, token, jwt', max_length=200, verbose_name='Chave do Token na Resposta'),
        ),
        migrations.AddField(
            model_name='fontedados',
            name='auth_url_relativa',
            field=models.CharField(blank=True, help_text='Caminho do endpoint de login. Ex: /oauth/token ou /api/v1/auth/login', max_length=500, verbose_name='URL de Login (relativa)'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='http_status_code',
            field=models.IntegerField(default=0, verbose_name='HTTP Status Code'),
        ),
        migrations.AlterField(
            model_name='credencialfonte',
            name='headers_customizados',
            field=models.JSONField(blank=True, default=dict, help_text='Ex: {"Accept": "application/json"}', verbose_name='Headers Fixos (JSON)'),
        ),
        migrations.AlterField(
            model_name='credencialfonte',
            name='token_atual',
            field=models.TextField(blank=True, verbose_name='Token Ativo (gerenciado pelo sistema)'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='metodo_http',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='Método HTTP'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='nome',
            field=models.CharField(help_text='Nome descritivo. Ex: Contratos Ativos', max_length=200, verbose_name='Nome do Endpoint'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='parametros_default',
            field=models.JSONField(blank=True, default=dict, help_text='Parâmetros fixos enviados em toda requisição.', verbose_name='Parâmetros / Body Padrão (JSON)'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='url_relativa',
            field=models.CharField(help_text='Ex: /api/v1/contratos', max_length=500, verbose_name='URL Relativa'),
        ),
        migrations.AlterField(
            model_name='fontedados',
            name='metodo_autenticacao',
            field=models.CharField(choices=[('none', 'Sem Autenticação'), ('basic', 'Basic Auth'), ('jwt', 'Token JWT (Auto-renovação)'), ('bearer', 'Bearer Token (Estático)'), ('api_key', 'API Key'), ('oauth2', 'OAuth 2.0')], default='none', max_length=50, verbose_name='Estratégia de Autenticação'),
        ),
        migrations.AlterField(
            model_name='fontedados',
            name='url_base',
            field=models.URLField(blank=True, help_text='Ex: https://api.exemplo.com.br', max_length=500, null=True, verbose_name='URL Base da API'),
        ),
    ]
