# Generated by Django 5.1.2 on 2026-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_dados', '0002_alter_endpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialfonte',
            name='senha_api',
            field=models.CharField(blank=True, max_length=500, verbose_name='Senha / Client Secret'),
        ),
    ]
