# Generated by Django 5.1.2 on 2026-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_dados', '0003_revert_encrypted_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='fontedados',
            name='mensagem_ultimo_teste',
            field=models.TextField(blank=True, verbose_name='Mensagem do Último Teste'),
        ),
        migrations.AddField(
            model_name='fontedados',
            name='ultimo_status_http',
            field=models.IntegerField(blank=True, null=True, verbose_name='Último HTTP Status'),
        ),
        migrations.AddField(
            model_name='fontedados',
            name='ultimo_teste',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Teste de Conexão'),
        ),
    ]
