# Generated by Django 5.1.2 on 2026-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_dados', '0004_add_status_conexao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialfonte',
            name='headers_customizados',
            field=models.JSONField(blank=True, default=dict, help_text='Ex: {"Accept": "application/json"}', null=True, verbose_name='Headers Fixos (JSON)'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='configuracao_layout',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Configuração de Layout'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='schema',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Schema (Metadados)'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='headers_override',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Headers Extras (sobrepõe os globais)'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='parametros_default',
            field=models.JSONField(blank=True, default=dict, help_text='Parâmetros fixos enviados em toda requisição.', null=True, verbose_name='Parâmetros / Body Padrão (JSON)'),
        ),
        migrations.AlterField(
            model_name='fontedados',
            name='auth_payload_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Campos adicionais além de username/password. Ex: {"grant_type": "password"}', null=True, verbose_name='Payload Extra de Login (JSON)'),
        ),
    ]
