# Generated by Django 5.1.2 on 2026-01-08 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instrumentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('a_iniciar', 'A Iniciar'), ('em_andamento', 'Em Andamento'), ('atrasado', 'Atrasado'), ('em_validacao', 'Em Validação'), ('finalizado', 'Finalizado')], default='a_iniciar', max_length=15, verbose_name='Status')),
                ('percentual_cumprido', models.IntegerField(default=0, help_text='Percentual de conclusão da ação (0-100)', verbose_name='Percentual Cumprido (%)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão Real')),
                ('periodicidade', models.CharField(choices=[('unica', 'Única'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='unica', max_length=15, verbose_name='Periodicidade')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('dias_antecedencia_alerta', models.IntegerField(blank=True, default=None, help_text='Número de dias antes do prazo para gerar alerta (opcional)', null=True, verbose_name='Dias de Antecedência para Alerta')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('acoes_predecessoras', models.ManyToManyField(blank=True, help_text='Ações que devem ser concluídas antes desta', related_name='acoes_sucessoras', to='acoes.acao', verbose_name='Ações Predecessoras')),
                ('executores', models.ManyToManyField(blank=True, help_text='Usuários que executam a ação (pode ser vários)', related_name='acoes_executor', to=settings.AUTH_USER_MODEL, verbose_name='Executores')),
                ('obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='instrumentos.obrigacao', verbose_name='Obrigação')),
                ('responsavel', models.ForeignKey(help_text='Responsável pela ação (apenas 1)', on_delete=django.db.models.deletion.PROTECT, related_name='acoes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('tipo_acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes_v2', to='core.tipoacao', verbose_name='Tipo de Ação')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['data_inicio', 'prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('concluido', models.BooleanField(default=False)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='acoes.acao')),
            ],
        ),
    ]
