# Generated by Django 5.1.2 on 2026-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Item de Checklist', 'verbose_name_plural': 'Itens de Checklist'},
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
