# Generated by Django 5.1.2 on 2025-10-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
        ('instrumentos', '0002_instrumento_nup_arquivoinstrumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='instrumentos.instrumento', verbose_name='Instrumento'),
        ),
    ]
