# Generated by Django 5.1.2 on 2025-10-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_acao_instrumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'ordering': ['data_fim_prevista', 'nome'], 'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.RemoveField(
            model_name='acao',
            name='prazo_cumprimento',
        ),
        migrations.AlterField(
            model_name='acao',
            name='data_fim_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim Prevista'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='dias_antecedencia_alerta',
            field=models.IntegerField(blank=True, default=None, help_text='Número de dias antes do prazo para gerar alerta (opcional)', null=True, verbose_name='Dias de Antecedência para Alerta'),
        ),
    ]
