# Generated by Django 5.1.2 on 2026-01-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_alter_checklistitem_options_checklistitem_ordem'),
        ('instrumentos', '0002_alter_obrigacao_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='obrigacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='instrumentos.obrigacao', verbose_name='Obrigação'),
        ),
    ]
