# Generated by Django 5.1.2 on 2026-01-27 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_alter_acao_obrigacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='evidencias/docs/%Y/%m/')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Documento')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='acoes.acao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento da Ação',
                'verbose_name_plural': 'Documentos da Ação',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='AcaoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='evidencias/fotos/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=255, verbose_name='Legenda')),
                ('data_registro', models.DateTimeField(blank=True, null=True, verbose_name='Data do Registro')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('coordenadas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenadas GPS')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='acoes.acao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Foto da Ação',
                'verbose_name_plural': 'Fotos da Ação',
                'ordering': ['-data_envio'],
            },
        ),
    ]
