# Generated by Django 5.1.2 on 2026-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_acaodocumento_acaofoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaodocumento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Documento'),
        ),
    ]
