# Generated by Django 5.1.2 on 2026-02-05 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0005_alter_acaodocumento_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoMarcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título/Identificação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descritivo da Ocorrência')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcadores', to='acoes.acao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Marcador de Mapa',
                'verbose_name_plural': 'Marcadores de Mapa',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='acaofoto',
            name='marcador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='acoes.acaomarcador', verbose_name='Marcador Associado'),
        ),
    ]
