# Generated by Django 5.1.2 on 2026-02-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0006_acaomarcador_acaofoto_marcador'),
        ('entidades', '0003_remove_entidade_cpf_representante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='entidade',
            field=models.ForeignKey(blank=True, help_text='Entidade fiscalizada sobre qual esta ação foi aplicada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_resultado', to='entidades.entidade', verbose_name='Entidade'),
        ),
        migrations.AddField(
            model_name='acao',
            name='justificativa_resultado',
            field=models.TextField(blank=True, help_text='Justificativa para o resultado informado', null=True, verbose_name='Justificativa do Resultado'),
        ),
        migrations.AddField(
            model_name='acao',
            name='resultado',
            field=models.CharField(blank=True, choices=[('atendido', 'Atendido'), ('parcialmente_atendido', 'Parcialmente Atendido'), ('nao_atendido', 'Não Atendido')], help_text='Indica se a entidade fiscalizada atendeu ao que foi solicitado pela ação', max_length=25, null=True, verbose_name='Resultado'),
        ),
    ]
