# Generated by Django 5.1.2 on 2026-02-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0007_acao_resultado_entidade_justificativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Conformidade')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conformidades', to='acoes.acao')),
            ],
            options={
                'verbose_name': 'Conformidade',
                'verbose_name_plural': 'Conformidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('status', models.IntegerField(choices=[(0, 'Neutro'), (1, 'Conforme'), (-1, 'Não Conforme')], default=0, verbose_name='Estado de Verificação')),
                ('ordem', models.IntegerField(default=0)),
                ('conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='acoes.conformidade')),
            ],
            options={
                'verbose_name': 'Item de Conformidade',
                'verbose_name_plural': 'Itens de Conformidade',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Constatacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Descrição da Constatação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constatacoes', to='acoes.itemconformidade')),
            ],
            options={
                'verbose_name': 'Constatação',
                'verbose_name_plural': 'Constatações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='acaofoto',
            name='item_conformidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='acoes.itemconformidade', verbose_name='Item de Conformidade'),
        ),
    ]
