# Generated by Django 5.1.2 on 2026-02-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0008_conformidade_itemconformidade_constatacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformidadeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template de Conformidade',
                'verbose_name_plural': 'Templates de Conformidade',
            },
        ),
        migrations.CreateModel(
            name='ItemConformidadeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('ordem', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='acoes.conformidadetemplate')),
            ],
            options={
                'verbose_name': 'Item de Template',
                'verbose_name_plural': 'Itens de Template',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
