# Generated by Django 5.1.2 on 2026-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0009_conformidadetemplate_itemconformidadetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conformidade',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Conformidade', 'verbose_name_plural': 'Conformidades'},
        ),
        migrations.AddField(
            model_name='conformidade',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
