# Generated by Django 5.1.2 on 2026-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0010_alter_conformidade_options_conformidade_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformidade',
            name='constatacao',
            field=models.TextField(blank=True, verbose_name='Constatações do Grupo'),
        ),
    ]
