# Generated by Django 5.1.2 on 2026-01-08 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_acao_atrasada', models.BooleanField(default=True, verbose_name='Notificar Ação Atrasada')),
                ('notificar_acao_vencendo', models.BooleanField(default=True, verbose_name='Notificar Ação Vencendo')),
                ('notificar_acao_nova', models.BooleanField(default=True, verbose_name='Notificar Nova Ação')),
                ('notificar_obrigacao', models.BooleanField(default=True, verbose_name='Notificar Obrigação')),
                ('notificar_comentario', models.BooleanField(default=True, verbose_name='Notificar Comentário')),
                ('enviar_email', models.BooleanField(default=False, help_text='Receber notificações por e-mail', verbose_name='Enviar E-mail')),
                ('frequencia_email', models.CharField(choices=[('imediato', 'Imediato'), ('diario', 'Resumo Diário'), ('semanal', 'Resumo Semanal')], default='diario', max_length=20, verbose_name='Frequência de E-mail')),
                ('tocar_som', models.BooleanField(default=True, help_text='Tocar som ao receber notificação', verbose_name='Tocar Som')),
                ('mostrar_toast', models.BooleanField(default=True, help_text='Mostrar notificação visual (toast)', verbose_name='Mostrar Toast')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acao_atrasada', 'Ação Atrasada'), ('acao_vencendo_hoje', 'Ação Vencendo Hoje'), ('acao_a_vencer', 'Ação a Vencer'), ('acao_nova', 'Nova Ação'), ('obrigacao_vencendo', 'Obrigação Vencendo'), ('instrumento_expirando', 'Instrumento Expirando'), ('comentario', 'Novo Comentário'), ('atribuicao', 'Ação Atribuída'), ('mudanca_status', 'Mudança de Status')], max_length=50, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('link', models.CharField(help_text='URL para onde a notificação leva', max_length=200, verbose_name='Link')),
                ('acao_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Ação')),
                ('obrigacao_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Obrigação')),
                ('instrumento_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Instrumento')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Notificação será removida após esta data', null=True, verbose_name='Data de Expiração')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['usuario', 'lida'], name='alertas_not_usuario_2e67c7_idx'), models.Index(fields=['usuario', 'data_criacao'], name='alertas_not_usuario_9cde96_idx'), models.Index(fields=['tipo', 'usuario'], name='alertas_not_tipo_a89ede_idx')],
            },
        ),
    ]
