# Generated by Django 5.1.2 on 2025-10-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='alertas_not_usuario_2e67c7_idx',
            old_name='alertas_not_usuario_lida_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='alertas_not_usuario_9cde96_idx',
            old_name='alertas_not_usuario_data_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='alertas_not_tipo_a89ede_idx',
            old_name='alertas_not_tipo_usuario_idx',
        ),
    ]
