# Generated by Django 5.1.2 on 2026-01-08 12:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('core', '0001_initial'),
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.IntegerField(choices=[(0, 'Admin'), (1, 'Diretoria'), (2, 'Assessoria'), (3, 'Coordenação'), (4, 'Usuário Comum'), (5, 'Visualizador')], default=4, help_text='Define o nível de acesso e permissões do usuário', verbose_name='Perfil de Acesso')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor/Departamento')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('senha_temporaria', models.BooleanField(default=False, help_text='Se True, usuário será forçado a trocar senha no próximo login', verbose_name='Senha Temporária')),
                ('ativo', models.BooleanField(default=True, verbose_name='Usuário Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('diretoria', models.ForeignKey(blank=True, help_text='Diretoria principal do usuário (obrigatório para perfis 1-5)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_diretoria', to='core.diretoria', verbose_name='Diretoria')),
                ('diretorias_visualizacao', models.ManyToManyField(blank=True, help_text='Diretorias que o visualizador pode acessar (apenas para perfil 5)', related_name='visualizadores', to='core.diretoria', verbose_name='Diretorias para Visualização')),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='entidades.entidade', verbose_name='Entidade')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('subunidade', models.ForeignKey(blank=True, help_text='Subunidade específica (obrigatório para perfis 2, 3, 4)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.subunidade', verbose_name='Subunidade')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['perfil'], name='usuarios_us_perfil_3e93e4_idx'), models.Index(fields=['diretoria'], name='usuarios_us_diretor_86086d_idx'), models.Index(fields=['subunidade'], name='usuarios_us_subunid_94c467_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
