# Generated by Django 5.1.2 on 2026-01-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Admin do Sistema'), (1, 'Gestor (Diretor)'), (2, 'Gestor (Assessor)'), (3, 'Técnico (Coordenador)'), (4, 'Técnico (Executor)'), (5, 'Visualizador (Auditor)')], default=4, help_text='Define o nível de acesso e permissões do usuário', verbose_name='Perfil de Acesso'),
        ),
    ]
