# Generated by Django 5.1.2 on 2025-10-31 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subunidade'),
        ('usuarios', '0003_atualizar_perfis_e_campos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usuario',
            new_name='usuarios_us_perfil_3e93e4_idx',
            old_name='usuarios_us_perfil_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario',
            new_name='usuarios_us_diretor_86086d_idx',
            old_name='usuarios_us_direto_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario',
            new_name='usuarios_us_subunid_94c467_idx',
            old_name='usuarios_us_subuni_idx',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='subunidade',
            field=models.ForeignKey(blank=True, help_text='Subunidade específica (obrigatório para perfis 2, 3, 4)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.subunidade', verbose_name='Subunidade'),
        ),
    ]
