# Generated by Django 5.2.7 on 2025-10-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, help_text='Upload do logo da entidade (PNG, JPG)', null=True, upload_to='entidades/logos/', verbose_name='Logo da Entidade')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('encerrada', 'Encerrada')], default='ativa', max_length=10, verbose_name='Status')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Principal')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('site', models.URLField(blank=True, verbose_name='Website')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cidade', models.CharField(default='Campo Grande', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='MS', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('representante_legal', models.CharField(max_length=200, verbose_name='Representante Legal')),
                ('cpf_representante', models.CharField(max_length=14, verbose_name='CPF do Representante')),
                ('email_representante', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Representante')),
                ('telefone_representante', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Representante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('tipo_entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='core.tipoentidade', verbose_name='Tipo de Entidade')),
                ('tipo_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='core.tiposervico', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['razao_social'],
            },
        ),
    ]
