# Generated by Django 5.1.2 on 2026-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cpf_representante',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Representante'),
        ),
    ]
