# Generated by Django 5.1.2 on 2026-01-15 14:48

import entidades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_entidade_cpf_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='cpf_representante',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='email_representante',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='telefone_representante',
        ),
        migrations.AlterField(
            model_name='entidade',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload do logo da entidade (PNG, JPG)', null=True, upload_to=entidades.models.Entidade.upload_logo_path, verbose_name='Logo da Entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Representante Legal'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
