# Generated by Django 5.1.2 on 2026-02-10 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamadaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Camada')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo_kml', models.FileField(upload_to='kml_referencias/', verbose_name='Arquivo KML')),
                ('cor_marcador', models.CharField(default='#3388ff', help_text='Cor HEX (ex: #3388ff)', max_length=7, verbose_name='Cor dos Pontos')),
                ('icone', models.CharField(default='circle', help_text='Nome do ícone (ex: circle, square)', max_length=50, verbose_name='Ícone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Camada de Referência',
                'verbose_name_plural': 'Camadas de Referência',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PontoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Ponto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Longitude')),
                ('camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='georeferencias.camadareferencia')),
            ],
            options={
                'verbose_name': 'Ponto de Referência',
                'verbose_name_plural': 'Pontos de Referência',
            },
        ),
    ]
