# Generated by Django 5.1.2 on 2026-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoreferencia',
            options={'verbose_name': 'Elemento de Referência', 'verbose_name_plural': 'Elementos de Referência'},
        ),
        migrations.AddField(
            model_name='pontoreferencia',
            name='coordenadas_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Coordenadas (JSON)'),
        ),
        migrations.AddField(
            model_name='pontoreferencia',
            name='estilo_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Estilo Customizado (JSON)'),
        ),
        migrations.AddField(
            model_name='pontoreferencia',
            name='tipo_geometria',
            field=models.CharField(choices=[('Point', 'Ponto'), ('LineString', 'Linha'), ('Polygon', 'Polígono')], default='Point', max_length=20, verbose_name='Tipo de Geometria'),
        ),
        migrations.AlterField(
            model_name='pontoreferencia',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Latitude (Âncora)'),
        ),
        migrations.AlterField(
            model_name='pontoreferencia',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Longitude (Âncora)'),
        ),
        migrations.AlterField(
            model_name='pontoreferencia',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Elemento'),
        ),
    ]
