# Generated by Django 5.1.2 on 2026-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencias', '0002_alter_pontoreferencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camadareferencia',
            name='cor_marcador',
            field=models.CharField(blank=True, default='#3388ff', help_text='Usada se o KML não tiver estilos', max_length=7, verbose_name='Cor Padrão (Fallback)'),
        ),
        migrations.AlterField(
            model_name='camadareferencia',
            name='icone',
            field=models.CharField(blank=True, default='circle', help_text='Emoji ou nome de ícone', max_length=50, verbose_name='Ícone Padrão'),
        ),
    ]
