# Generated by Django 5.1.2 on 2026-08-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencias', '0003_alter_camadareferencia_cor_marcador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camadareferencia',
            name='cor_marcador',
        ),
        migrations.RemoveField(
            model_name='camadareferencia',
            name='icone',
        ),
    ]
