upstream web_app {
    server web:8000;
}

server {
    listen 80;
    
    # O underscore '_' serve como um "pega-tudo" (catch-all) no Nginx.
    # Ele responde a qualquer IP (ex: 10.6.0.208) ou domínio que chegar na porta 80.
    server_name _; 

    client_max_body_size 100M;

    # Arquivos Estáticos (CSS, JS, Imagens do Sistema)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Arquivos de Mídia (Uploads do Usuário)
    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Repasse de Requisições para a Aplicação Django (Gunicorn)
    location / {
        proxy_pass http://web_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        # Importante: Como não há HTTPS, removemos o cabeçalho X-Forwarded-Proto $scheme 
        # para evitar confusão de segurança no Django.
    }
}
