# Generated by Django 5.2.7 on 2025-10-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Instrumento')),
                ('objeto', models.TextField(verbose_name='Objeto do Instrumento')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_inicio', models.DateField(verbose_name='Data de Início da Vigência')),
                ('data_fim', models.DateField(verbose_name='Data de Fim da Vigência')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do instrumento, se aplicável', max_digits=15, null=True, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('em_renovacao', 'Em Renovação')], default='vigente', max_length=15, verbose_name='Status')),
                ('arquivo', models.FileField(blank=True, help_text='Upload do PDF do instrumento', null=True, upload_to='instrumentos/', verbose_name='Arquivo do Instrumento')),
                ('periodicidade_revisao_tarifaria', models.IntegerField(blank=True, default=12, null=True, verbose_name='Periodicidade de Revisão Tarifária (meses)')),
                ('data_proxima_revisao', models.DateField(blank=True, null=True, verbose_name='Data da Próxima Revisão Tarifária')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='core.diretoria', verbose_name='Diretoria Responsável')),
                ('entidades', models.ManyToManyField(help_text='Selecione uma ou mais entidades vinculadas a este instrumento', related_name='instrumentos', to='entidades.entidade', verbose_name='Entidades Vinculadas')),
                ('tipo_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='core.tipoinstrumento', verbose_name='Tipo de Instrumento')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Obrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Obrigação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('clausula_referencia', models.CharField(blank=True, help_text='Ex: Cláusula 5.2, Item 3.4, etc', max_length=50, verbose_name='Cláusula de Referência')),
                ('recorrente', models.BooleanField(default=False, help_text='Se marcado, esta obrigação não será marcada como cumprida automaticamente', verbose_name='Obrigação Recorrente')),
                ('data_vencimento', models.DateField(blank=True, help_text='Data limite para cumprimento (se aplicável)', null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('cumprida', 'Cumprida'), ('vencida', 'Vencida')], default='pendente', max_length=15, verbose_name='Status')),
                ('cumprida', models.BooleanField(default=False, verbose_name='Cumprida')),
                ('data_cumprimento', models.DateField(blank=True, null=True, verbose_name='Data de Cumprimento')),
                ('dias_antecedencia_alerta', models.IntegerField(default=30, help_text='Número de dias antes do vencimento para gerar alerta', verbose_name='Dias de Antecedência para Alerta')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes', to='instrumentos.instrumento', verbose_name='Instrumento')),
                ('tipo_obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obrigacoes', to='core.tipoobrigacao', verbose_name='Tipo de Obrigação')),
            ],
            options={
                'verbose_name': 'Obrigação',
                'verbose_name_plural': 'Obrigações',
                'ordering': ['data_vencimento', 'titulo'],
            },
        ),
    ]
