# Generated by Django 5.1.2 on 2026-01-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacao',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obrigacoes', to='instrumentos.instrumento', verbose_name='Instrumento'),
        ),
    ]
