# Generated by Django 5.2.7 on 2025-10-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='nup',
            field=models.CharField(blank=True, help_text='Número Único de Protocolo do sistema E-MS', max_length=50, verbose_name='NUP (E-MS)'),
        ),
        migrations.CreateModel(
            name='ArquivoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='instrumentos/arquivos/', verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='instrumentos.instrumento', verbose_name='Instrumento')),
            ],
            options={
                'verbose_name': 'Arquivo do Instrumento',
                'verbose_name_plural': 'Arquivos do Instrumento',
                'ordering': ['-data_upload'],
            },
        ),
    ]
