# Generated by Django 5.1.2 on 2026-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_alter_obrigacao_instrumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrigacao',
            name='cumprida',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='data_cumprimento',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='dias_antecedencia_alerta',
        ),
        migrations.AddField(
            model_name='obrigacao',
            name='percentual_atendimento',
            field=models.IntegerField(default=0, help_text='Média ponderada baseada nos itens de checklist das ações', verbose_name='Percentual de Atendimento (%)'),
        ),
        migrations.AddField(
            model_name='obrigacao',
            name='prazo_dias',
            field=models.IntegerField(default=0, help_text='Número de dias a partir da data de início do instrumento', verbose_name='Prazo (Dias)'),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data limite para cumprimento (calculada ou manual)', null=True, verbose_name='Data de Vencimento'),
        ),
    ]
