# Generated by Django 5.1.2 on 2026-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0003_remove_obrigacao_cumprida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome do Instrumento'),
        ),
    ]
