# Generated by Django 5.1.2 on 2026-03-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instrumentos', '0003_remove_obrigacao_cumprida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='subunidade',
            field=models.ForeignKey(blank=True, help_text='Subunidade responsável pela gestão do instrumento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='core.subunidade', verbose_name='Subunidade Responsável'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome do Instrumento'),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='percentual_atendimento',
            field=models.IntegerField(default=0, help_text='Percentual de atendimento definido manualmente pelo gestor (0 a 100)', verbose_name='Percentual de Atendimento (%)'),
        ),
    ]
