# Generated by Django 5.1.2 on 2026-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instrumentos', '0004_instrumento_subunidade_alter_instrumento_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='subunidades',
            field=models.ManyToManyField(blank=True, related_name='instrumentos_multi', to='core.subunidade', verbose_name='Subunidades Gestoras'),
        ),
    ]
