# Generated by Django 5.1.2 on 2026-03-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0005_instrumento_subunidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='subunidade',
        ),
    ]
