# Generated by Django 5.1.2 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0006_remove_instrumento_subunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacao',
            name='clausula_referencia',
            field=models.CharField(blank=True, help_text='Ex: Cláusula 5.2, Item 3.4, etc', max_length=200, verbose_name='Cláusula de Referência'),
        ),
    ]
